---
title: "Zip Code Mapping"
author: "Jacquelyn Neal"
date: "April 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r packages,message=FALSE,warning=FALSE}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
```


```{r USA}
usa <- map_data("usa")
states <- map_data("state")
ggplot() + 
  geom_polygon(data = states, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  coord_fixed(1.3)
```

```{r}
library(geosphere)
zipCodes <- read.csv('~/Documents/zipCodeMapping/zipCodesUS.csv',stringsAsFactors = FALSE,header=TRUE)
colnames(zipCodes) <- c('zip','lat','long') 
zipCodes <- zipCodes[zipCodes$lat<50 & zipCodes$lat>20 & zipCodes$long>-130,]
zipCodes$Distance <- (distm(zipCodes[,c('long','lat')], zipCodes[zipCodes$zip==37214,c('long','lat')], fun=distVincentyEllipsoid)/1000)/1.609


ggplot() +
  geom_point(data = zipCodes, aes(x=long,y=lat,colour = Distance,size=Distance)) +
  scale_colour_gradient(limits = c(0, 2500),low='#001933',high='white') +
  scale_size_continuous(range = c(0.25,1),guide = FALSE) +
  geom_polygon(data = states, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  coord_fixed(1.3) +
  geom_point(data=zipCodes,aes(x=-86.67087,y=36.16219),colour='#CCE5FF',size=2,shape=9) +
  theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank())
```


```{r}
coord_US <- matrix(0,3,ncol=4)
coord_US[1,] <- c(-86.67087, 36.16219, -122.3321,47.6062)
coord_US[2,] <- c(-86.67087, 36.16219, -74.0059, 40.7128)
coord_US[3,] <- c(-86.67087, 36.16219, -81.3792, 28.5383)
coord_US <- data.frame(coord_US)
colnames(coord_US) <- c("Long1","Lat1","Long2","Lat2")

cities <- matrix(0,4,ncol=3)
cities[1,] <- c(-86.67087, 36.16219, 'Nashville')
cities[2,] <- c(-122.3321,47.6062,'Seattle')
cities[3,] <- c(-74.0059, 40.7128,'New York City')
cities[4,] <- c(-81.3792, 28.5383, 'Orlando')
cities <- data.frame(cities)
colnames(cities) <- c("Long","Lat","City")
cities$Long <- as.character(cities$Long)
cities$Long <- as.numeric(cities$Long)
cities$Lat <- as.character(cities$Lat)
cities$Lat <- as.numeric(cities$Lat)

ggplot() +
  geom_polygon(data = states , aes(x=long, y = lat, group = group), fill = NA, color = "black") +
  geom_point(data = zipCodes, aes(x=long,y=lat,colour = Distance),size=1) +
  scale_colour_gradient(limits=c(0,3000),low='#001933',high='white',guide_legend(title="Distance (mi)")) + 
  #scale_size_continuous(range=c(1,5),guide=FALSE)  + 
  coord_fixed(1.3) +
  geom_polygon(data = states , aes(x=long, y = lat, group = group), fill = NA, color = "black") +
  geom_point(data=cities,aes(x=Long[1],y= Lat[1]),colour='#99CCFF',size=4,shape=9) +
  geom_curve(data=coord_US,aes(x=Long1, y=Lat1, xend=Long2, yend=Lat2),colour='#FF0074',
            arrow=arrow(angle=30,length=unit(0.4,"cm")), curvature = 0.3,size=1) +
  geom_text(data=cities,aes(x=Long+3.5,y= Lat+1.95,label=City),size=5.5,colour=c('gold'), fontface=2)+ #,'#D4AF37','#D4AF37','#D4AF37'),fontface=2) +
  theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank())
```

```{r Tenn}
dat.tenn <- states[states$region=='tennessee',]
tenn.zipcodes <- seq(37010,38589,by=1)

coord_TN <- matrix(0,3,ncol=4)
coord_TN[1,] <- c(-86.67087, 36.16219, -90.0490,35.1495)
coord_TN[2,] <- c(-86.67087, 36.16219, -85.3097, 35.0456)
coord_TN[3,] <- c(-86.67087, 36.16219, -83.9207, 35.9606)
coord_TN <- data.frame(coord_TN)
colnames(coord_TN) <- c("Long1","Lat1","Long2","Lat2")

cities_TN <- matrix(0,4,ncol=3)
cities_TN[1,] <- c(-86.67087, 36.16219, 'Nashville')
cities_TN[2,] <- c(-90.0490, 35.1495,'Memphis')
cities_TN[3,] <- c(-85.3097, 35.0456,'Chattanooga')
cities_TN[4,] <- c(-83.9207, 35.9606,'Knoxville')
cities_TN <- data.frame(cities_TN)
colnames(cities_TN) <- c("Long","Lat","City")
cities_TN$Long <- as.character(cities_TN$Long)
cities_TN$Long <- as.numeric(cities_TN$Long)
cities_TN$Lat <- as.character(cities_TN$Lat)
cities_TN$Lat <- as.numeric(cities_TN$Lat)

ggplot() +
  geom_polygon(data = dat.tenn , aes(x=long, y = lat, group = group), fill = NA, color = "black") +
  geom_point(data = zipCodes[zipCodes$zip %in% tenn.zipcodes,], aes(x=long,y=lat,colour = Distance),size=5) +
  scale_colour_gradient(low='#001933',high='white',guide_legend(title="Distance (mi)")) + 
  #scale_size_continuous(range=c(1,5),guide=FALSE)  + 
  coord_fixed(1.3) +
  geom_polygon(data = dat.tenn , aes(x=long, y = lat, group = group), fill = NA, color = "black") +
  geom_curve(data=coord_TN,aes(x=Long1, y=Lat1, xend=Long2, yend=Lat2),colour='#FFB266',
            arrow=arrow(angle=30,length=unit(0.4,"cm")), curvature = 0.3,size=1) +
  geom_point(data=cities_TN,aes(x=Long[1],y= Lat[1]),size=5,colour='#99CCFF',shape=9) +
  geom_text(data=cities_TN,aes(x=Long+0.45,y= Lat+0.15,label=City),size=5.5,colour='gold',fontface=2) +
  theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank())
```

